x-common-service: &common-service
  entrypoint:
    - bash
    - -c
    - |
      echo 'Giving Kafka a bit of time to start up…'
      sleep 20
      venv/bin/python start.py /shared/config.ini
  volumes:
    - ./ci-inetd/shared:/shared
  networks:
    - ci-inetd-network

services:
  # ci-arch-ui:
  #   build: ./ci-arch-ui
  #   image: ci-arch-ui
  #   container_name: ci-arch-ui
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - ci-inetd-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
     - "2181:2181"
    networks:
      - ci-inetd-network

  broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker
    ports:
      - "9092:9092"
    expose:
     - "29092"
    depends_on:
      - zookeeper
    env_file: ./ci-inetd/modules/broker/config/.env
    networks:
      - ci-inetd-network

  daemons-service:
    build: ./daemons-service/
    image: daemons-service
    entrypoint: 
        venv/bin/python start.py
    container_name: daemons-service
    environment:
      - MODULE_NAME=daemons-service
    ports:
      - 8000:8000
    networks:
      - ci-inetd-network

  ci-inetd-monitor:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-monitor
    image: ci-inetd-monitor
    container_name: ci-inetd-monitor
    environment:
      - MODULE_NAME=ci-inetd-monitor

  ci-inetd-port_listener:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-port_listener
    image: ci-inetd-port_listener
    container_name: ci-inetd-port_listener
    environment:
      - MODULE_NAME=ci-inetd-port_listener
      - MODULE_PORT=8003
    ports:
      - "8003:8003"

  ci-inetd-request_forwarder:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-request_forwarder
    image: ci-inetd-request_forwarder
    container_name: ci-inetd-request_forwarder
    environment:
      - MODULE_NAME=ci-inetd-request_forwarder
      - MODULE_PORT=8004
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8004:8004"

  ci-inetd-config_parser:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-config_parser
    image: ci-inetd-config_parser
    container_name: ci-inetd-config_parser
    environment:
      - MODULE_NAME=ci-inetd-config_parser
      - MODULE_PORT=8005
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8005:8005"

  ci-inetd-request_verifier:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-request_verifier
    image: ci-inetd-request_verifier
    container_name: ci-inetd-request_verifier
    environment:
      - MODULE_NAME=ci-inetd-request_verifier
      - MODULE_PORT=8006
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8006:8006"

  ci-inetd-log_analyzer:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-log_analyzer
    image: ci-inetd-log_analyzer
    container_name: ci-inetd-log_analyzer
    environment:
      - MODULE_NAME=ci-inetd-log_analyzer
      - MODULE_PORT=8007
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8007:8007"

  ci-inetd-permission_executor:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-permission_executor
    image: ci-inetd-permission_executor
    container_name: ci-inetd-permission_executor
    environment:
      - MODULE_NAME=ci-inetd-permission_executor
      - MODULE_PORT=8008
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8008:8008"

  ci-inetd-executor:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-executor
    image: ci-inetd-executor
    container_name: ci-inetd-executor
    environment:
      - MODULE_NAME=ci-inetd-executor
      - MODULE_PORT=8009
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8009:8009"

  ci-inetd-executor_entity_sender:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-executor_entity_sender
    image: ci-inetd-executor_entity_sender
    container_name: ci-inetd-executor_entity_sender
    environment:
      - MODULE_NAME=ci-inetd-executor_entity_sender
      - MODULE_PORT=8010
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8010:8010"

  ci-inetd-action_manager:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-action_manager
    image: ci-inetd-action_manager
    container_name: ci-inetd-action_manager
    environment:
      - MODULE_NAME=ci-inetd-action_manager
      - MODULE_PORT=8011
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8011:8011"

  ci-inetd-status_manager:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-status_manager
    image: ci-inetd-status_manager
    container_name: ci-inetd-status_manager
    environment:
      - MODULE_NAME=ci-inetd-status_manager
      - MODULE_PORT=8012
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8012:8012"

  ci-inetd-id_status:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-id_status
    image: ci-inetd-id_status
    container_name: ci-inetd-id_status
    environment:
      - MODULE_NAME=ci-inetd-id_status
      - MODULE_PORT=8013
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8013:8013"

  ci-inetd-port_status:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-port_status
    image: ci-inetd-port_status
    container_name: ci-inetd-port_status
    environment:
      - MODULE_NAME=ci-inetd-port_status
      - MODULE_PORT=8014
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8014:8014"

  ci-inetd-critical_entity_sender:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-critical_entity_sender
    image: ci-inetd-critical_entity_sender
    container_name: ci-inetd-critical_entity_sender
    environment:
      - MODULE_NAME=ci-inetd-critical_entity_sender
      - MODULE_PORT=8015
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8015:8015"

  ci-inetd-critical_executor:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-critical_executor
    image: ci-inetd-critical_executor
    container_name: ci-inetd-critical_executor
    environment:
      - MODULE_NAME=ci-inetd-critical_executor
      - MODULE_PORT=8016
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8016:8016"

  ci-inetd-permission_terminator:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-permission_terminator
    image: ci-inetd-permission_terminator
    container_name: ci-inetd-permission_terminator
    environment:
      - MODULE_NAME=ci-inetd-permission_terminator
      - MODULE_PORT=8017
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8017:8017"

  ci-inetd-terminator:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-terminator
    image: ci-inetd-terminator
    container_name: ci-inetd-terminator
    environment:
      - MODULE_NAME=ci-inetd-terminator
      - MODULE_PORT=8018
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8018:8018"

  ci-inetd-log_receiver:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-log_receiver
    image: ci-inetd-log_receiver
    container_name: ci-inetd-log_receiver
    environment:
      - MODULE_NAME=ci-inetd-log_receiver
      - MODULE_PORT=8019
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8019:8019"

  ci-inetd-log_forwarder:
    <<: *common-service
    build: ./ci-inetd/modules/ci-inetd-log_forwarder
    image: ci-inetd-log_forwarder
    container_name: ci-inetd-log_forwarder
    environment:
      - MODULE_NAME=ci-inetd-log_forwarder
      - MODULE_PORT=8020
    volumes:
      - ./ci-inetd/shared:/shared
    ports:
      - "8020:8020"

networks:
  ci-inetd-network:
    driver: bridge